# Generated by Django 5.1.6 on 2025-04-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_remove_result_is_absent_quiz_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
    ]
