# Generated by Django 5.1.6 on 2025-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_remove_quiz_category_remove_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('literature', 'Literature')], default='math', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
